// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYDmbu5g91QEpvTI_9nyjEfwIPwnipo6Y',
    appId: '1:68817406937:web:d558d5efd23fd27d33e7c8',
    messagingSenderId: '68817406937',
    projectId: 'rocketdelivery-d182c',
    authDomain: 'rocketdelivery-d182c.firebaseapp.com',
    storageBucket: 'rocketdelivery-d182c.firebasestorage.app',
    measurementId: 'G-SFHWXRT3QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWS_0RZQA_56WkMQe0o0oiA1ljzy_0B6U',
    appId: '1:68817406937:android:6ac77ec55b8a1f6a33e7c8',
    messagingSenderId: '68817406937',
    projectId: 'rocketdelivery-d182c',
    storageBucket: 'rocketdelivery-d182c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWH-u7saE1VH2Zh5NiPAlYc4gGDSlVf8',
    appId: '1:68817406937:ios:0ea1b2075979f0a233e7c8',
    messagingSenderId: '68817406937',
    projectId: 'rocketdelivery-d182c',
    storageBucket: 'rocketdelivery-d182c.firebasestorage.app',
    iosBundleId: 'com.example.fastDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNWH-u7saE1VH2Zh5NiPAlYc4gGDSlVf8',
    appId: '1:68817406937:ios:0ea1b2075979f0a233e7c8',
    messagingSenderId: '68817406937',
    projectId: 'rocketdelivery-d182c',
    storageBucket: 'rocketdelivery-d182c.firebasestorage.app',
    iosBundleId: 'com.example.fastDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYDmbu5g91QEpvTI_9nyjEfwIPwnipo6Y',
    appId: '1:68817406937:web:dd05d115895c07c533e7c8',
    messagingSenderId: '68817406937',
    projectId: 'rocketdelivery-d182c',
    authDomain: 'rocketdelivery-d182c.firebaseapp.com',
    storageBucket: 'rocketdelivery-d182c.firebasestorage.app',
    measurementId: 'G-PRSZX9S6LK',
  );
}
